// AUTO-GENERATED by scripts/mineGroups.ts — do not edit by hand.
// Strategy groups whose joint BUY signal cleared 80%+ win rate over 5
// years (same trade plan as the single-strategy backtest) AND held >=70% on an
// 18-month holdout. A group fires when EVERY member signals BUY
// on the same bar.
export interface SignalGroup {
  id: string;
  members: string[];
  horizon: number;
  winRate: number;
  trades: number;
  avgReturn: number;
  testWinRate: number;
  testTrades: number;
}

export const SIGNAL_GROUPS: SignalGroup[] = [
  { id: "combo-1", members: ["martingale","graham-mr-market","stochastic-momentum","qm-signal-rolling"], horizon: 21, winRate: 90, trades: 50, avgReturn: 6.193, testWinRate: 90.5, testTrades: 21 },
  { id: "combo-2", members: ["murphy-rsi-70-30","wizard-trend-breakout","obv-trend-confirm","adx-trend-strength","aroon-trend-change","qm-ma-momentum-cross","qm-multifactor-momentum"], horizon: 21, winRate: 87.3, trades: 55, avgReturn: 2.885, testWinRate: 71.4, testTrades: 14 },
  { id: "combo-3", members: ["murphy-rsi-70-30","murphy-support-resistance","murphy-volume-confirmation","market-regime-detector","qm-ma-momentum-cross","qm-multifactor-momentum"], horizon: 21, winRate: 88.4, trades: 43, avgReturn: 3.139, testWinRate: 72.7, testTrades: 11 },
  { id: "combo-4", members: ["murphy-rsi-70-30","wizard-trend-breakout","obv-trend-confirm","adx-trend-strength","aroon-trend-change","market-regime-detector","qm-donchian-breakout","qm-ma-momentum-cross","qm-abcd-pattern","qm-ema-trend-stack"], horizon: 21, winRate: 87.5, trades: 48, avgReturn: 2.944, testWinRate: 71.4, testTrades: 14 },
  { id: "combo-5", members: ["murphy-head-shoulders","wizard-schwartz-momentum","market-regime-detector","qm-abcd-pattern","qm-ema-trend-stack"], horizon: 21, winRate: 82.1, trades: 134, avgReturn: 2.292, testWinRate: 70.8, testTrades: 24 },
  { id: "combo-6", members: ["graham-margin-of-safety","fear-greed-momentum","gap-continuation","stochastic-momentum"], horizon: 10, winRate: 85.1, trades: 67, avgReturn: 5.64, testWinRate: 84.6, testTrades: 39 },
  { id: "combo-7", members: ["martingale","swing-buying-options","graham-margin-of-safety","cci-extreme-reversal","mfi-money-flow","qm-zscore-reversion","qm-hurst-statarb"], horizon: 10, winRate: 87.8, trades: 41, avgReturn: 3.878, testWinRate: 75, testTrades: 12 },
  { id: "combo-8", members: ["murphy-rsi-70-30","murphy-support-resistance","murphy-volume-confirmation","market-regime-detector","qm-donchian-breakout","qm-ma-momentum-cross","qm-abcd-pattern","qm-ema-trend-stack"], horizon: 21, winRate: 87.8, trades: 41, avgReturn: 3.012, testWinRate: 72.7, testTrades: 11 },
  { id: "combo-9", members: ["fractal-trading","graham-margin-of-safety","adl-accumulation","aroon-trend-change","force-index-momentum","qm-ma-momentum-cross","qm-volatility-regime"], horizon: 10, winRate: 87.5, trades: 40, avgReturn: 4.327, testWinRate: 80, testTrades: 10 },
  { id: "combo-10", members: ["murphy-rsi-70-30","wizard-trend-breakout","obv-trend-confirm","market-regime-detector","qm-donchian-breakout","qm-ma-momentum-cross","qm-multifactor-momentum"], horizon: 21, winRate: 86, trades: 50, avgReturn: 2.812, testWinRate: 71.4, testTrades: 14 },
  { id: "combo-11", members: ["murphy-rsi-70-30","wizard-trend-breakout","obv-trend-confirm","adx-trend-strength","relative-strength-market","qm-multifactor-momentum","qm-ema-trend-stack"], horizon: 21, winRate: 83.8, trades: 74, avgReturn: 2.435, testWinRate: 73.7, testTrades: 19 },
  { id: "combo-12", members: ["cpr-trend","murphy-support-resistance","murphy-roc","bogle-trend-following","institutional-accumulation","gap-continuation","volatility-breakout"], horizon: 21, winRate: 84.7, trades: 59, avgReturn: 2.673, testWinRate: 73.3, testTrades: 15 },
];
