// Educational content for all indicators, strategies, and concepts

export interface TutorialIndicator {
  id: string;
  name: string;
  category: "Trend" | "Momentum" | "Volume" | "Volatility" | "Oscillator";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  shortDesc: string;
  formula: string;
  interpretation: string[];
  buySignal: string;
  sellSignal: string;
  bestFor: string;
  limitations: string;
  exampleStock: string;
  exampleIndicators: string[];
  proTip: string;
}

export interface TutorialStrategy {
  id: string;
  name: string;
  book: string;
  category: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  shortDesc: string;
  logic: string[];
  entryRules: string[];
  exitRules: string[];
  riskManagement: string;
  bestMarketCondition: string;
  avoidWhen: string;
  realExample: string;
  exampleStock: string;
  exampleIndicators: string[];
  winRate: string;
  timeframe: string;
  proTip: string;
}

export interface TutorialConcept {
  id: string;
  name: string;
  category: "Basics" | "Technical" | "Fundamental" | "Psychology" | "Risk" | "Market Structure";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  shortDesc: string;
  explanation: string[];
  keyPoints: string[];
  commonMistakes: string[];
  realExample: string;
  relatedConcepts: string[];
}

export const TUTORIAL_INDICATORS: TutorialIndicator[] = [
  {
    id: "sma",
    name: "Simple Moving Average (SMA)",
    category: "Trend",
    difficulty: "Beginner",
    shortDesc: "Average of closing prices over N periods. The most basic trend indicator.",
    formula: "SMA = (P1 + P2 + ... + Pn) / n, where P = closing price, n = period",
    interpretation: [
      "Price ABOVE SMA = Uptrend. The stock is performing better than its recent average.",
      "Price BELOW SMA = Downtrend. The stock is underperforming its recent average.",
      "SMA 20 = Short-term trend (1 month). React to quick moves.",
      "SMA 50 = Medium-term trend (2.5 months). Filters out daily noise.",
      "SMA 200 = Long-term trend (1 year). The big picture. Institutional investors watch this closely.",
      "When shorter SMA crosses above longer SMA = Golden Cross (bullish).",
      "When shorter SMA crosses below longer SMA = Death Cross (bearish).",
    ],
    buySignal: "Price crosses above SMA 200, or SMA 50 crosses above SMA 200 (Golden Cross). These are strong long-term buy signals.",
    sellSignal: "Price crosses below SMA 200, or SMA 50 crosses below SMA 200 (Death Cross). Consider exiting or hedging.",
    bestFor: "Identifying overall trend direction. Works best in trending markets.",
    limitations: "Lags behind price (it's based on past data). Gives false signals in choppy/sideways markets. Not useful for timing exact entries.",
    exampleStock: "RELIANCE",
    exampleIndicators: ["sma20", "sma50", "sma200"],
    proTip: "Don't use SMA alone. Combine with RSI or MACD for confirmation. The 200-SMA is the most watched level globally - when Nifty touches it, expect a reaction.",
  },
  {
    id: "ema",
    name: "Exponential Moving Average (EMA)",
    category: "Trend",
    difficulty: "Beginner",
    shortDesc: "Like SMA but gives more weight to recent prices. Reacts faster to price changes.",
    formula: "EMA = Price(today) x Multiplier + EMA(yesterday) x (1 - Multiplier), where Multiplier = 2/(period+1)",
    interpretation: [
      "EMA reacts FASTER than SMA to price changes because it weights recent prices more heavily.",
      "EMA 9 = Very short-term (swing trading). Tracks price closely.",
      "EMA 21 = Short-term trend. Popular for swing traders.",
      "When 9-EMA crosses above 21-EMA = Bullish crossover (buy signal).",
      "When 9-EMA crosses below 21-EMA = Bearish crossover (sell signal).",
      "Price bouncing off EMA = The EMA is acting as support/resistance.",
    ],
    buySignal: "9-EMA crosses above 21-EMA with price above both. Volume should confirm the crossover.",
    sellSignal: "9-EMA crosses below 21-EMA with price below both.",
    bestFor: "Swing trading, catching trend changes early. Better than SMA for short-term trades.",
    limitations: "More prone to false signals than SMA because it's more sensitive. Can whipsaw in choppy markets.",
    exampleStock: "TCS",
    exampleIndicators: ["ema9", "ema21"],
    proTip: "In a strong uptrend, price pulls back to 21-EMA and bounces - that's your buy entry. If it breaks below 21-EMA, the trend may be weakening.",
  },
  {
    id: "rsi",
    name: "Relative Strength Index (RSI)",
    category: "Momentum",
    difficulty: "Beginner",
    shortDesc: "Measures speed and magnitude of price changes on a 0-100 scale. The king of oscillators.",
    formula: "RSI = 100 - (100 / (1 + RS)), where RS = Average Gain / Average Loss over 14 periods",
    interpretation: [
      "RSI > 70 = OVERBOUGHT. The stock has risen too fast and may pull back. But in strong uptrends, RSI can stay above 70 for weeks!",
      "RSI < 30 = OVERSOLD. The stock has fallen too fast and may bounce. But in crashes, RSI can stay below 30 for days.",
      "RSI = 50 is the centerline. Above 50 = bullish momentum. Below 50 = bearish momentum.",
      "RSI DIVERGENCE is the most powerful signal: Price makes new low but RSI makes higher low = Bullish divergence (price about to reverse up).",
      "RSI making lower highs while price makes higher highs = Bearish divergence (rally about to fail).",
      "RSI crossing above 30 from below = Buy signal (leaving oversold).",
      "RSI crossing below 70 from above = Sell signal (leaving overbought).",
    ],
    buySignal: "RSI drops below 30, then crosses back above 30. Best when combined with price at support level or lower Bollinger Band.",
    sellSignal: "RSI rises above 70, then crosses back below 70. Or bearish divergence: price new high but RSI lower high.",
    bestFor: "Finding overbought/oversold stocks. Best indicator for mean-reversion trades. Works in all timeframes.",
    limitations: "In strong trends, RSI stays overbought/oversold for extended periods - don't sell just because RSI is 70+ in a bull run. Always confirm with price action.",
    exampleStock: "INFY",
    exampleIndicators: ["rsi"],
    proTip: "The best RSI buy signal is: RSI drops to 25-30 + price touches lower Bollinger Band + volume spike = capitulation buy. This has a 70%+ success rate historically.",
  },
  {
    id: "macd",
    name: "MACD (Moving Average Convergence Divergence)",
    category: "Momentum",
    difficulty: "Intermediate",
    shortDesc: "Shows relationship between two EMAs. Identifies trend direction, momentum, and potential reversals.",
    formula: "MACD Line = 12-EMA - 26-EMA. Signal Line = 9-EMA of MACD Line. Histogram = MACD Line - Signal Line.",
    interpretation: [
      "MACD Line above Signal Line = Bullish momentum. Below = Bearish momentum.",
      "MACD crossing above Signal Line = BUY signal (bullish crossover).",
      "MACD crossing below Signal Line = SELL signal (bearish crossover).",
      "Histogram growing = Momentum accelerating. Histogram shrinking = Momentum slowing.",
      "Both lines above zero = Bullish trend. Both below zero = Bearish trend.",
      "MACD crossing above zero line = Major bullish shift.",
      "MACD DIVERGENCE with price = Very strong reversal signal. Same concept as RSI divergence but using MACD.",
    ],
    buySignal: "MACD crosses above Signal Line while both are below zero (bullish reversal from oversold). The histogram turning positive confirms.",
    sellSignal: "MACD crosses below Signal Line while both are above zero (momentum failing at highs).",
    bestFor: "Trend following and momentum trading. Great for catching the middle of big moves. Works on daily and weekly charts.",
    limitations: "Lagging indicator - it confirms trends rather than predicting them. Can give false signals in sideways markets. Not good for timing exact tops/bottoms.",
    exampleStock: "HDFCBANK",
    exampleIndicators: ["macd"],
    proTip: "The most reliable MACD signal is when the histogram shrinks to near zero, then expands in the opposite direction. This 'histogram reversal' often catches major trend changes.",
  },
  {
    id: "bollinger",
    name: "Bollinger Bands",
    category: "Volatility",
    difficulty: "Intermediate",
    shortDesc: "A channel around price that expands/contracts with volatility. Shows if price is relatively high or low.",
    formula: "Middle Band = 20-SMA. Upper Band = 20-SMA + (2 x StdDev). Lower Band = 20-SMA - (2 x StdDev).",
    interpretation: [
      "Price at UPPER band = Relatively expensive. Not necessarily a sell - in uptrends, price 'walks' along the upper band.",
      "Price at LOWER band = Relatively cheap. Not necessarily a buy - in downtrends, price 'walks' along the lower band.",
      "SQUEEZE: Bands narrow = Low volatility. A BIG move is coming but direction unknown. Watch for breakout direction.",
      "EXPANSION: Bands widen = High volatility. The move is happening. Trade in the direction of the breakout.",
      "Price moving from lower band to middle band = Strength returning. From upper to middle = Weakness.",
      "%B indicator: (Price - Lower) / (Upper - Lower). >1 = above upper band. <0 = below lower band.",
      "Band Width: (Upper - Lower) / Middle. Low width = squeeze. High width = volatile.",
    ],
    buySignal: "Price touches lower band + RSI below 30 + volume spike = Strong buy. Or: Squeeze breakout upward with volume.",
    sellSignal: "Price touches upper band + RSI above 70 + bearish candle = Take profit. Or: Price fails at upper band multiple times.",
    bestFor: "Identifying volatility regimes, mean-reversion trades, and breakout setups. Works great with RSI.",
    limitations: "Bands expand AFTER the move starts, not before. In strong trends, price can stay outside bands. Don't blindly buy at lower band in a downtrend.",
    exampleStock: "TATAMOTORS",
    exampleIndicators: ["bb"],
    proTip: "The Bollinger Squeeze is one of the most reliable setups: when Band Width hits a 6-month low, a big move is 1-2 weeks away. Combine with MACD for direction.",
  },
  {
    id: "supertrend",
    name: "Supertrend",
    category: "Trend",
    difficulty: "Beginner",
    shortDesc: "A trailing stop-loss indicator that flips between bullish (green) and bearish (red). Very popular in India.",
    formula: "Upper Band = (High+Low)/2 + (Multiplier x ATR). Lower Band = (High+Low)/2 - (Multiplier x ATR). Default: Period=10, Multiplier=3.",
    interpretation: [
      "Supertrend GREEN (below price) = BULLISH. Hold long positions. The green line acts as a trailing stop loss.",
      "Supertrend RED (above price) = BEARISH. Stay out or go short. The red line acts as resistance.",
      "When Supertrend flips from RED to GREEN = BUY signal. This is a trend reversal.",
      "When Supertrend flips from GREEN to RED = SELL signal. Exit long positions.",
      "The distance between price and Supertrend = strength of trend. Wider gap = stronger trend.",
      "Supertrend uses ATR, so it adapts to volatility. Wider in volatile markets, tighter in calm markets.",
    ],
    buySignal: "Supertrend flips from red to green (below candle). Best when accompanied by a bullish candle with above-average volume.",
    sellSignal: "Supertrend flips from green to red (above candle). Exit immediately - this is a clear trend change signal.",
    bestFor: "Positional and swing trading. Very popular among Indian retail traders. Simple to follow - green = buy, red = sell.",
    limitations: "Gives frequent false signals in sideways markets. The 3x ATR default can be too wide for intraday. Adjust multiplier: 2x for intraday, 3x for positional.",
    exampleStock: "SBIN",
    exampleIndicators: ["supertrend"],
    proTip: "Use Supertrend as your stop-loss, not your entry signal. Enter on other signals (RSI, MACD, pattern) and use Supertrend to trail your stop. Exit only when Supertrend flips.",
  },
  {
    id: "atr",
    name: "Average True Range (ATR)",
    category: "Volatility",
    difficulty: "Intermediate",
    shortDesc: "Measures volatility by looking at the full range of price movement. Essential for position sizing and stop losses.",
    formula: "True Range = Max(High-Low, |High-PrevClose|, |Low-PrevClose|). ATR = 14-period average of True Range.",
    interpretation: [
      "ATR is NOT a directional indicator - it only measures HOW MUCH a stock moves, not which direction.",
      "High ATR = The stock is volatile, moving a lot each day. Use wider stops.",
      "Low ATR = The stock is calm, moving little. Use tighter stops.",
      "Rising ATR = Volatility increasing. Often happens at trend starts and trend ends.",
      "Falling ATR = Volatility decreasing. Often leads to a breakout (low volatility precedes big moves).",
      "Use ATR for stop-loss: Stop = Entry - 1.5 x ATR for swing trades, 2 x ATR for positional.",
      "Use ATR for position sizing: Risk per trade / (ATR x multiplier) = number of shares.",
    ],
    buySignal: "ATR contracting to a low point (squeeze) followed by expansion upward = Volatility breakout buy.",
    sellSignal: "ATR extremely high after a big run = Exhaustion move. Consider taking profits as volatility peaks.",
    bestFor: "Setting stop losses, determining position size, identifying volatility regime. MUST-HAVE for risk management.",
    limitations: "Doesn't tell you direction. High ATR could mean big moves up OR down. Always combine with directional indicators.",
    exampleStock: "BAJFINANCE",
    exampleIndicators: ["bb"],
    proTip: "The 'ATR channel' strategy: Buy when price is above 20-SMA + 1.5xATR (breakout), stop at 20-SMA - 1xATR. This captures trending moves with managed risk.",
  },
  {
    id: "obv",
    name: "On Balance Volume (OBV)",
    category: "Volume",
    difficulty: "Intermediate",
    shortDesc: "Running total of volume that increases on up days and decreases on down days. Volume precedes price.",
    formula: "If Close > Previous Close: OBV = Previous OBV + Volume. If Close < Previous Close: OBV = Previous OBV - Volume.",
    interpretation: [
      "The key principle: VOLUME PRECEDES PRICE. Smart money acts before the crowd.",
      "OBV rising while price is flat = ACCUMULATION. Smart money is buying. Price will likely follow up.",
      "OBV falling while price is flat = DISTRIBUTION. Smart money is selling. Price will likely follow down.",
      "OBV making new high with price = CONFIRMATION. The uptrend is healthy.",
      "OBV NOT making new high while price does = DIVERGENCE. The rally is on thin volume. Weakening.",
      "OBV trend matters more than the absolute number. Compare the direction of OBV with price direction.",
    ],
    buySignal: "OBV rising while price is flat or falling (bullish divergence). Smart money accumulating before the move.",
    sellSignal: "OBV falling while price is rising (bearish divergence). Distribution happening - rally will fail.",
    bestFor: "Confirming breakouts (true breakout = OBV confirms), spotting accumulation/distribution before price moves.",
    limitations: "One big-volume day can distort the line. Doesn't work well for low-volume stocks. Use 20-SMA of OBV to smooth it.",
    exampleStock: "ITC",
    exampleIndicators: ["sma50"],
    proTip: "Before buying any breakout, check OBV. If OBV already broke out before price = genuine breakout. If OBV is flat/declining during price breakout = false breakout. This one filter alone saves money.",
  },
  {
    id: "stochastic",
    name: "Stochastic Oscillator",
    category: "Oscillator",
    difficulty: "Intermediate",
    shortDesc: "Shows where the current close is relative to the high-low range. %K (fast) and %D (slow) lines give crossover signals.",
    formula: "%K = 100 x (Close - Lowest Low) / (Highest High - Lowest Low) over 14 periods. %D = 3-period SMA of %K.",
    interpretation: [
      "%K above 80 = OVERBOUGHT zone. Stock is closing near the top of its range.",
      "%K below 20 = OVERSOLD zone. Stock is closing near the bottom of its range.",
      "%K crossing above %D in oversold zone = Strong BUY signal.",
      "%K crossing below %D in overbought zone = Strong SELL signal.",
      "Both lines rising from below 20 = Strong bullish momentum building.",
      "Stochastic divergence with price = Same concept as RSI divergence but often gives earlier signals.",
    ],
    buySignal: "%K crosses above %D below 20 (oversold crossover). Best when price is at support.",
    sellSignal: "%K crosses below %D above 80 (overbought crossover). Best when price is at resistance.",
    bestFor: "Range-bound markets, swing trading, timing entries in trending markets (buy pullbacks when Stochastic goes oversold in uptrend).",
    limitations: "In strong trends, Stochastic stays overbought/oversold for a long time - don't fight the trend. Use longer periods (21,7) to reduce false signals.",
    exampleStock: "MARUTI",
    exampleIndicators: ["sma50"],
    proTip: "The best Stochastic setup: In an uptrend (price above 50-SMA), wait for Stochastic to drop below 20, then buy when %K crosses above %D. This 'buy the dip' in a trend works 65%+ of the time.",
  },
  {
    id: "adx",
    name: "Average Directional Index (ADX)",
    category: "Trend",
    difficulty: "Advanced",
    shortDesc: "Measures STRENGTH of a trend, not direction. ADX above 25 = strong trend. Below 20 = no trend.",
    formula: "ADX = 14-period smoothed average of DX. DX = |+DI - -DI| / (+DI + -DI) x 100. +DI and -DI measure directional movement.",
    interpretation: [
      "ADX < 20 = NO TREND. Market is range-bound. Use mean-reversion strategies (RSI, Bollinger).",
      "ADX 20-25 = Trend DEVELOPING. Be alert for breakout.",
      "ADX 25-50 = STRONG TREND. Use trend-following strategies (Supertrend, MA crossovers).",
      "ADX > 50 = VERY STRONG trend (rare). Often near exhaustion point.",
      "+DI above -DI = Bullish direction. -DI above +DI = Bearish direction.",
      "+DI crossing above -DI with rising ADX = Strong buy. -DI crossing above +DI with rising ADX = Strong sell.",
      "ADX falling from high levels = Trend weakening. Consider taking profits.",
    ],
    buySignal: "+DI crosses above -DI while ADX is above 25 and rising. This is a confirmed trend buy.",
    sellSignal: "-DI crosses above +DI while ADX is above 25 and rising. Or ADX dropping from above 40 = trend exhaustion.",
    bestFor: "Deciding which TYPE of strategy to use. High ADX = trend following. Low ADX = mean reversion. This is the meta-indicator.",
    limitations: "ADX is a lagging indicator - by the time ADX confirms a strong trend, a chunk of the move is over. Rising ADX only means trend is strong, not which direction.",
    exampleStock: "BHARTIARTL",
    exampleIndicators: ["sma50", "sma200"],
    proTip: "ADX below 20 for 10+ days = volatility squeeze. When ADX starts rising from below 20, a major trend is about to begin. This is the calm before the storm.",
  },
  {
    id: "mfi",
    name: "Money Flow Index (MFI)",
    category: "Volume",
    difficulty: "Intermediate",
    shortDesc: "Volume-weighted RSI. Like RSI but includes volume data, making signals more reliable.",
    formula: "MFI = 100 - (100 / (1 + Money Flow Ratio)). Money Flow Ratio = Positive Money Flow / Negative Money Flow over 14 periods.",
    interpretation: [
      "MFI > 80 = OVERBOUGHT with heavy volume. Stronger signal than RSI alone.",
      "MFI < 20 = OVERSOLD with heavy selling volume. Strong buy zone.",
      "MFI incorporates volume, so it's better than RSI at detecting institutional activity.",
      "MFI divergence from price is very reliable - institutions can't hide large volume.",
      "MFI rising while price flat = Money flowing IN despite no price change. Accumulation.",
      "MFI falling while price flat = Money flowing OUT. Distribution happening.",
    ],
    buySignal: "MFI drops below 20 then recovers above 20. Volume-confirmed oversold bounce.",
    sellSignal: "MFI rises above 80 then drops below 80. Volume-confirmed overbought reversal.",
    bestFor: "Confirming RSI signals with volume. Spotting institutional buying/selling. More reliable than RSI for large-cap stocks.",
    limitations: "Needs reliable volume data (doesn't work well with thinly traded stocks). Can stay extreme in strong trends like RSI.",
    exampleStock: "ICICIBANK",
    exampleIndicators: ["rsi"],
    proTip: "When RSI says oversold AND MFI says oversold = double confirmation. This is the highest probability buy signal from oscillators. Both must agree.",
  },
  {
    id: "vwap",
    name: "VWAP (Volume Weighted Average Price)",
    category: "Volume",
    difficulty: "Beginner",
    shortDesc: "Average price weighted by volume. Institutional benchmark. THE most important intraday indicator.",
    formula: "VWAP = Cumulative(Typical Price x Volume) / Cumulative(Volume). Typical Price = (High + Low + Close) / 3.",
    interpretation: [
      "VWAP = The average price institutions paid today. It's their benchmark.",
      "Price ABOVE VWAP = Buyers in control. Institutions are profitable on the day. Bullish.",
      "Price BELOW VWAP = Sellers in control. Institutions are losing money today. Bearish.",
      "Price crossing above VWAP = Shift from bearish to bullish intraday. Buy signal.",
      "Price crossing below VWAP = Shift from bullish to bearish intraday. Sell signal.",
      "VWAP acts as dynamic support/resistance throughout the day.",
      "Resets every day - only valid for intraday use (our app uses a VWAP proxy for daily data).",
    ],
    buySignal: "Price dips below VWAP, then crosses back above it with rising volume. The classic 'VWAP reclaim' buy.",
    sellSignal: "Price fails to reclaim VWAP after opening below it. Or rejects VWAP from below multiple times.",
    bestFor: "Intraday trading. Understanding institutional positioning. Determining if you're buying at a good average price.",
    limitations: "Only valid intraday (resets daily). Less useful for positional/swing trading. Our app uses a proxy for daily charts.",
    exampleStock: "RELIANCE",
    exampleIndicators: ["sma20"],
    proTip: "Professional rule: Never buy above VWAP for intraday trades (you're paying more than the average). Wait for a pullback to VWAP to enter. This one rule improves intraday results dramatically.",
  },
];

export const TUTORIAL_CONCEPTS: TutorialConcept[] = [
  {
    id: "support-resistance",
    name: "Support & Resistance",
    category: "Technical",
    difficulty: "Beginner",
    shortDesc: "Price levels where buying pressure (support) or selling pressure (resistance) repeatedly stops price movement.",
    explanation: [
      "SUPPORT is a price level where demand is strong enough to prevent further price decline. Think of it as a floor.",
      "RESISTANCE is a price level where supply is strong enough to prevent further price increase. Think of it as a ceiling.",
      "These levels form because traders REMEMBER prices. If a stock bounced from ₹100 before, traders will buy again near ₹100.",
      "The more times a level is tested, the STRONGER it becomes. But eventually, all levels break.",
      "When support breaks, it becomes RESISTANCE (and vice versa). This 'role reversal' is one of the most reliable patterns.",
      "Round numbers (₹100, ₹500, ₹1000) are psychological support/resistance levels.",
      "Moving averages (50-SMA, 200-SMA) act as dynamic support/resistance that moves with price.",
    ],
    keyPoints: [
      "Support holds because buyers step in at that price",
      "Resistance holds because sellers step in at that price",
      "Volume confirms the level - high volume at a level makes it stronger",
      "Broken support becomes resistance, broken resistance becomes support",
      "The more touches, the stronger the level, but also the more likely to eventually break",
    ],
    commonMistakes: [
      "Treating support/resistance as exact prices instead of ZONES (use ranges, not precise numbers)",
      "Buying at support without confirming the level holds (wait for a bounce candle)",
      "Fighting a clear break of support/resistance - once broken with volume, the direction is confirmed",
      "Ignoring that old levels lose relevance over time - a support from 2 years ago matters less than one from last month",
    ],
    realExample: "Nifty at 20,000 is a major psychological resistance. When it first approached 20,000 in Sep 2023, it rejected and fell. When it finally broke above with volume in Dec 2023, 20,000 became support. Every pullback to 20,000 area was bought.",
    relatedConcepts: ["Trend Lines", "Fibonacci Retracement", "Pivot Points"],
  },
  {
    id: "trend-following",
    name: "Trend Following",
    category: "Technical",
    difficulty: "Beginner",
    shortDesc: "The principle that prices move in trends, and it's easier to profit by following the trend than predicting reversals.",
    explanation: [
      "UPTREND = Higher Highs and Higher Lows. Each peak is higher than the last. Each dip finds buyers at a higher level.",
      "DOWNTREND = Lower Highs and Lower Lows. Each rally fails at a lower level. Each dip goes deeper.",
      "SIDEWAYS = Price moves within a range. No clear direction. Most difficult to trade.",
      "'The trend is your friend' - the oldest rule in trading. 70% of profits come from riding trends.",
      "Enter in the direction of the trend on pullbacks. Don't try to pick tops or bottoms.",
      "A trend continues until it's PROVEN broken. Higher lows stop forming = uptrend broken.",
      "Use moving averages to define trend: Price above 200-SMA = long-term uptrend. Period.",
    ],
    keyPoints: [
      "Identify the trend first, then choose your strategy",
      "Buy pullbacks in uptrends, sell rallies in downtrends",
      "Never go against the trend on higher timeframes",
      "Trend-following strategies win ~40% of the time but the winners are BIG",
      "Combine with position sizing - ride winners long, cut losers fast",
    ],
    commonMistakes: [
      "Trying to catch the exact bottom or top (wait for trend confirmation)",
      "Selling too early in a strong trend because 'it's gone up too much'",
      "Using trend-following strategies in sideways markets (use ADX to filter)",
      "Ignoring the larger timeframe trend (daily uptrend matters more than hourly downtrend)",
    ],
    realExample: "Reliance from March 2020 (₹870) to Oct 2024 (₹3000+). Those who followed the trend with 200-SMA as guide rode a 250% move. Those who sold because 'RSI was overbought' missed out. The trend was up - simple.",
    relatedConcepts: ["Moving Averages", "ADX", "Supertrend", "Dow Theory"],
  },
  {
    id: "candlestick-basics",
    name: "Candlestick Patterns",
    category: "Technical",
    difficulty: "Beginner",
    shortDesc: "Japanese candlestick charts show Open, High, Low, Close in visual form. Patterns predict short-term price direction.",
    explanation: [
      "Each CANDLE shows 4 prices: Open (where trading started), Close (where it ended), High (highest point), Low (lowest point).",
      "GREEN/WHITE candle = Close > Open (price went UP during the period). BULLISH.",
      "RED/BLACK candle = Close < Open (price went DOWN during the period). BEARISH.",
      "The thick part is the BODY (open to close). The thin lines are SHADOWS/WICKS (extremes).",
      "Long body = Strong conviction. Short body = Indecision. Long wick = Rejection of that price level.",
      "HAMMER: Small body at top, long lower wick. At bottom of downtrend = bullish reversal. Buyers stepped in.",
      "SHOOTING STAR: Small body at bottom, long upper wick. At top of uptrend = bearish reversal. Sellers stepped in.",
      "ENGULFING: Current candle completely covers previous candle. Bullish engulfing at lows = strong buy.",
      "DOJI: Open = Close (cross shape). Indecision. After a trend = potential reversal.",
    ],
    keyPoints: [
      "Patterns are MORE reliable at support/resistance levels",
      "Volume confirms the pattern - bullish pattern + high volume = stronger signal",
      "Single candle patterns are weaker than 2-3 candle patterns",
      "Context matters - a hammer in a downtrend is bullish, in an uptrend it means nothing",
      "Don't trade patterns in isolation - combine with indicators",
    ],
    commonMistakes: [
      "Trading every doji/hammer without considering the trend context",
      "Ignoring volume - a hammer on low volume is unreliable",
      "Not waiting for confirmation candle (next candle should confirm the reversal)",
      "Over-complicating - focus on 4-5 key patterns, not all 100+",
    ],
    realExample: "HDFC Bank formed a bullish engulfing at ₹1400 support in March 2024 with 2x average volume. The next 3 months it rallied to ₹1700. The pattern + support + volume = high probability trade.",
    relatedConcepts: ["Support & Resistance", "Volume Confirmation", "Price Action"],
  },
  {
    id: "risk-management",
    name: "Risk Management",
    category: "Risk",
    difficulty: "Beginner",
    shortDesc: "THE most important concept in trading. How to protect your capital and survive long enough to profit.",
    explanation: [
      "Rule #1: Never risk more than 1-2% of your total capital on a single trade. If you have ₹10L, max risk per trade = ₹10,000-20,000.",
      "POSITION SIZING: Risk amount / (Entry - Stop Loss) = Number of shares. This is how professionals size trades.",
      "STOP LOSS: A pre-decided price where you exit to limit losses. Set it BEFORE entering the trade. No exceptions.",
      "RISK-REWARD RATIO: Only take trades where potential profit is at least 2x the potential loss (2:1 R:R).",
      "DIVERSIFICATION: Don't put all money in one stock. Spread across sectors. If one fails, others survive.",
      "DRAWDOWN: The peak-to-trough decline in your portfolio. Keep max drawdown under 20%. If you lose 50%, you need 100% to recover.",
      "COMPOUNDING: Protecting capital enables compounding. Even 15% annual return turns ₹10L into ₹40L in 10 years.",
    ],
    keyPoints: [
      "Capital preservation comes BEFORE profit making",
      "A 50% loss needs a 100% gain to recover - avoid large losses at all costs",
      "Position sizing is more important than entry timing",
      "Use ATR-based stops (1.5x ATR for swing, 2x ATR for positional)",
      "Maximum 5-6 positions at a time for active traders",
    ],
    commonMistakes: [
      "No stop loss - 'it will come back' is how accounts blow up",
      "Moving stop loss further away when trade goes against you (widening losses)",
      "Position size too large - one bad trade wipes out months of gains",
      "Averaging down on a losing trade without a plan",
      "Trading with money you can't afford to lose",
    ],
    realExample: "Trader A bets 20% of capital on one stock. It drops 30%. Portfolio down 6%. Trader B bets 5% with a stop loss at 10%. Same stock. Portfolio down 0.5%. Trader B survives to trade another day. Over 100 trades, this difference is the difference between survival and blowup.",
    relatedConcepts: ["ATR", "Position Sizing", "Stop Loss", "Drawdown"],
  },
  {
    id: "divergence",
    name: "Divergence (RSI/MACD)",
    category: "Technical",
    difficulty: "Intermediate",
    shortDesc: "When price and an indicator disagree about direction. One of the strongest reversal signals in technical analysis.",
    explanation: [
      "BULLISH DIVERGENCE: Price makes a LOWER low, but RSI/MACD makes a HIGHER low. The indicator is saying 'selling pressure is weakening even though price is still falling.' A bottom is near.",
      "BEARISH DIVERGENCE: Price makes a HIGHER high, but RSI/MACD makes a LOWER high. The indicator is saying 'buying pressure is weakening even though price is still rising.' A top is near.",
      "HIDDEN BULLISH DIVERGENCE: Price makes a higher low, but RSI makes a lower low. The trend is actually strengthening. Continuation signal.",
      "Divergence works because indicators measure MOMENTUM, not price. When momentum weakens, price follows.",
      "Divergence on HIGHER timeframes (weekly) is more reliable than on lower timeframes (15-min).",
      "Divergence needs CONFIRMATION - wait for a reversal candle before acting on divergence alone.",
    ],
    keyPoints: [
      "Regular divergence = reversal signal (trend about to change)",
      "Hidden divergence = continuation signal (trend about to resume)",
      "Works best at key support/resistance levels",
      "Multiple divergences (RSI + MACD both diverge) = stronger signal",
      "Divergence is a WARNING, not an immediate action signal - wait for confirmation",
    ],
    commonMistakes: [
      "Acting on divergence immediately without waiting for price confirmation",
      "Looking for divergence on very short timeframes (5-min divergences are unreliable)",
      "Confusing regular and hidden divergence",
      "Expecting divergence to work every time - it's probabilistic, not certain",
    ],
    realExample: "Nifty made a new low at 21,200 in March 2024, but RSI made a higher low (35 vs 28 from the previous dip). Classic bullish divergence. Nifty then rallied 15% to 24,400 over the next 3 months.",
    relatedConcepts: ["RSI", "MACD", "Momentum", "Reversal Patterns"],
  },
  {
    id: "volume-analysis",
    name: "Volume Analysis",
    category: "Technical",
    difficulty: "Intermediate",
    shortDesc: "Volume is the fuel of price movement. It confirms trends, validates breakouts, and reveals institutional activity.",
    explanation: [
      "VOLUME = Number of shares traded. High volume = high conviction. Low volume = low conviction.",
      "Price up + Volume up = HEALTHY uptrend. Both buyers and momentum agree. Continue holding.",
      "Price up + Volume down = WEAK rally. Price is rising but fewer people are buying. Be cautious.",
      "Price down + Volume up = PANIC SELLING. Heavy distribution. Could be capitulation (bottom) or trend break.",
      "Price down + Volume down = QUIET decline. Not much selling pressure. Often a pullback, not a trend reversal.",
      "BREAKOUT + High volume = REAL breakout. The move will likely continue.",
      "BREAKOUT + Low volume = FALSE breakout. The move will likely reverse. This single rule saves money.",
      "Volume spikes at bottoms = Capitulation (everyone who wanted to sell has sold). Often marks THE bottom.",
      "Volume declines over time in a rally = Buyers exhausting. The rally is running on fumes.",
    ],
    keyPoints: [
      "Volume confirms what price is doing",
      "Never trust a breakout without above-average volume",
      "Climax volume after extended trends = exhaustion (reversal likely)",
      "Low-volume pullbacks in uptrends = healthy (dip buying opportunity)",
      "OBV, MFI, and A/D Line are technical ways to analyze volume",
    ],
    commonMistakes: [
      "Ignoring volume entirely and only looking at price",
      "Buying breakouts without checking if volume confirms",
      "Confusing high volume at tops with bullish signals (it's often distribution)",
      "Not comparing current volume to AVERAGE volume (use 20-day average as baseline)",
    ],
    realExample: "Tata Motors broke above ₹750 resistance in Nov 2023 with 3x average volume. This confirmed the breakout. The stock then rallied to ₹1100 in 4 months. Compare: It had tried to break ₹750 in Sep 2023 on normal volume and failed, pulling back to ₹650.",
    relatedConcepts: ["OBV", "MFI", "Accumulation/Distribution", "Breakout Trading"],
  },
  {
    id: "fibonacci",
    name: "Fibonacci Retracement",
    category: "Technical",
    difficulty: "Intermediate",
    shortDesc: "Price levels based on Fibonacci ratios (23.6%, 38.2%, 50%, 61.8%) where pullbacks tend to find support.",
    explanation: [
      "After a big move, prices tend to retrace (pull back) a predictable percentage before continuing.",
      "23.6% retracement = Shallow pullback. Very strong trend. Buy here in strong uptrends.",
      "38.2% retracement = Normal pullback. The most common retracement in healthy trends. First level to watch.",
      "50% retracement = Not actually Fibonacci but widely used. 'The market retraces half.' Strong buy/sell zone.",
      "61.8% retracement = The 'Golden Ratio'. Deep pullback. If this holds, the trend is still intact. If it breaks, the trend may be over.",
      "78.6% retracement = Very deep pullback. The trend is weak but not yet broken. Last chance for bulls.",
      "Draw Fibonacci from the SWING LOW to SWING HIGH (uptrend) or HIGH to LOW (downtrend).",
      "Fibonacci works because enough traders use them that they become self-fulfilling prophecies.",
    ],
    keyPoints: [
      "38.2% and 61.8% are the most important levels",
      "Fibonacci levels are ZONES, not exact prices",
      "Combine with other support/resistance for stronger confluence",
      "Works on any timeframe but more reliable on daily/weekly",
      "Extensions (127.2%, 161.8%) help set profit targets after a breakout",
    ],
    commonMistakes: [
      "Drawing Fibonacci on random points instead of clear swing highs/lows",
      "Expecting price to stop exactly at a Fibonacci level (use zones)",
      "Using Fibonacci alone without other confirmation (combine with RSI, volume)",
      "Ignoring the trend - Fibonacci works for pullbacks IN a trend, not reversals",
    ],
    realExample: "HDFC Bank rallied from ₹1400 to ₹1800. Pullback found support exactly at 61.8% retracement (₹1553). RSI was at 35 at that level. Bounce from there took it to ₹1900. The 61.8% + RSI oversold = textbook buy.",
    relatedConcepts: ["Support & Resistance", "Trend Following", "Swing Trading"],
  },
  {
    id: "market-sentiment",
    name: "Market Sentiment & Psychology",
    category: "Psychology",
    difficulty: "Beginner",
    shortDesc: "Markets are driven by two emotions: Fear and Greed. Understanding crowd psychology is the edge that separates winners from losers.",
    explanation: [
      "FEAR makes people sell at the worst time (near bottoms). GREED makes people buy at the worst time (near tops).",
      "When everyone is bullish and talking about stocks at parties = market is near a TOP. 'Be fearful when others are greedy.'",
      "When everyone is scared and saying 'market will crash more' = market is near a BOTTOM. 'Be greedy when others are fearful.'",
      "VIX (Volatility Index) measures fear. VIX > 30 = high fear = buying opportunity. VIX < 15 = complacency = be careful.",
      "India VIX below 12 = extreme calm before a storm. Above 25 = extreme fear (often marks bottoms).",
      "FII (Foreign Institutional Investor) flows drive Indian markets. FII buying = market up. FII selling = market down.",
      "Retail investors tend to buy high and sell low. Institutions tend to buy low (accumulate) and sell high (distribute).",
      "The market makes the MOST people wrong at turning points. It feels worst to buy when you should buy.",
    ],
    keyPoints: [
      "Sentiment extremes are contrarian indicators",
      "Follow institutional money (FII/DII flows), not retail sentiment",
      "Keep a trading journal to track your own emotional decisions",
      "Have a pre-decided plan and follow it regardless of how you FEEL",
      "The best buys feel the scariest and the best sells feel the hardest",
    ],
    commonMistakes: [
      "Panic selling during corrections (selling at exactly the wrong time)",
      "FOMO buying after a big rally ('I'll miss out!')",
      "Revenge trading - trying to recover losses immediately",
      "Listening to TV news for trading decisions (news reflects consensus, not edge)",
    ],
    realExample: "March 2020 COVID crash: India VIX hit 83. Nifty fell to 7,500. Media said 'worst crisis in 100 years.' Retail investors panic sold. FIIs started buying from April. By December 2020, Nifty was at 14,000 (86% up). The maximum fear point was the maximum opportunity.",
    relatedConcepts: ["VIX", "FII/DII Flows", "Contrarian Investing", "Risk Management"],
  },
];
