// AUTO-GENERATED by scripts/backtestEtfCalls.ts — do not edit by hand.
// 5-year, event-based backtest of the ETF composite call (transitions only,
// 21-bar cooldown, 18-month holdout). BUY-side calls carry a real
// positive edge and are served with their measured stats. SELL-side calls
// graded 40.2% (IN) / 44% (US) — worse than a coin flip — and were
// REMOVED from the site: scores below the BUY bar render as HOLD.
export interface EtfCallStat {
  n: number;
  hitRate21: number;
  testHitRate21: number;
  hitRate63: number;
  avgReturn63: number;
}

export const ETF_CALL_STATS: Record<"IN" | "US", Record<"BUY" | "STRONG_BUY", EtfCallStat>> = {
  "IN": {
    "BUY": {
      "n": 1356,
      "hitRate21": 56.9,
      "testHitRate21": 58.3,
      "hitRate63": 60.8,
      "avgReturn63": 3.263
    },
    "STRONG_BUY": {
      "n": 1169,
      "hitRate21": 59.5,
      "testHitRate21": 56.9,
      "hitRate63": 61.9,
      "avgReturn63": 3.201
    }
  },
  "US": {
    "BUY": {
      "n": 1724,
      "hitRate21": 54.2,
      "testHitRate21": 62.3,
      "hitRate63": 54.7,
      "avgReturn63": 0.963
    },
    "STRONG_BUY": {
      "n": 1472,
      "hitRate21": 53.5,
      "testHitRate21": 55.7,
      "hitRate63": 56.3,
      "avgReturn63": 1.513
    }
  }
};
