// AUTO-GENERATED by scripts/backtestCues.ts — do not edit by hand.
// 5-year backtest of global-cue signals against what they claim to predict
// (gap = next session's opening gap, day = close-to-close, fwd5 = 5-day drift).
// Singles bar: >=60% hit rate, >=100 occurrences, >=55% on an
// 18-month holdout. Combos bar: >=90% with >=75% holdout.
// Generated 2026-07-03.
export interface VerifiedCue {
  id: string;
  label: string;
  outcome: "gap" | "day" | "fwd5";
  hitRate: number;
  n: number;
  testHitRate: number;
  avgMove: number;
}

export interface GapCombo {
  members: string[];
  labels: string[];
  outcome: string;
  hitRate: number;
  n: number;
  testHitRate: number;
  testN: number;
  avgMove: number;
}

export const VERIFIED_GLOBAL_CUES: Record<"IN" | "US", VerifiedCue[]> = {
  "IN": [
    {
      "id": "us-close",
      "label": "US market close (>0.3%)",
      "outcome": "gap",
      "hitRate": 75.6,
      "n": 877,
      "testHitRate": 72.2,
      "avgMove": 0.299
    },
    {
      "id": "us-close-strong",
      "label": "US strong close (>1.5%)",
      "outcome": "gap",
      "hitRate": 87.6,
      "n": 170,
      "testHitRate": 82.2,
      "avgMove": 0.626
    },
    {
      "id": "nasdaq-divergence",
      "label": "Nasdaq vs S&P divergence (>0.5%)",
      "outcome": "gap",
      "hitRate": 70.2,
      "n": 346,
      "testHitRate": 73.6,
      "avgMove": 0.286
    },
    {
      "id": "europe-prev",
      "label": "Europe previous close (>0.5%)",
      "outcome": "gap",
      "hitRate": 68.8,
      "n": 564,
      "testHitRate": 69.4,
      "avgMove": 0.228
    },
    {
      "id": "dxy",
      "label": "Dollar index move (>0.3%, inverse)",
      "outcome": "gap",
      "hitRate": 61.9,
      "n": 548,
      "testHitRate": 63.3,
      "avgMove": 0.173
    },
    {
      "id": "vix-spike",
      "label": "VIX move (>10%, inverse)",
      "outcome": "gap",
      "hitRate": 79.5,
      "n": 171,
      "testHitRate": 77.3,
      "avgMove": 0.495
    }
  ],
  "US": [
    {
      "id": "asia-day",
      "label": "Asia same-day close (>0.3%)",
      "outcome": "gap",
      "hitRate": 63.6,
      "n": 911,
      "testHitRate": 70.5,
      "avgMove": 0.148
    }
  ]
};

export const VERIFIED_GAP_COMBOS: Record<"IN" | "US", GapCombo[]> = {
  "IN": [
    {
      "members": [
        "us-close",
        "us-close-strong",
        "dxy"
      ],
      "labels": [
        "US market close (>0.3%)",
        "US strong close (>1.5%)",
        "Dollar index move (>0.3%, inverse)"
      ],
      "outcome": "gap",
      "n": 71,
      "hitRate": 95.8,
      "testN": 11,
      "testHitRate": 90.9,
      "avgMove": 0.88
    },
    {
      "members": [
        "us-close-strong",
        "nasdaq-divergence",
        "europe-prev"
      ],
      "labels": [
        "US strong close (>1.5%)",
        "Nasdaq vs S&P divergence (>0.5%)",
        "Europe previous close (>0.5%)"
      ],
      "outcome": "gap",
      "n": 63,
      "hitRate": 92.1,
      "testN": 10,
      "testHitRate": 80,
      "avgMove": 0.665
    },
    {
      "members": [
        "us-close",
        "nasdaq-divergence",
        "europe-prev"
      ],
      "labels": [
        "US market close (>0.3%)",
        "Nasdaq vs S&P divergence (>0.5%)",
        "Europe previous close (>0.5%)"
      ],
      "outcome": "gap",
      "n": 119,
      "hitRate": 91.6,
      "testN": 25,
      "testHitRate": 92,
      "avgMove": 0.555
    },
    {
      "members": [
        "us-close",
        "us-close-strong",
        "nasdaq-divergence"
      ],
      "labels": [
        "US market close (>0.3%)",
        "US strong close (>1.5%)",
        "Nasdaq vs S&P divergence (>0.5%)"
      ],
      "outcome": "gap",
      "n": 100,
      "hitRate": 91,
      "testN": 26,
      "testHitRate": 84.6,
      "avgMove": 0.69
    },
    {
      "members": [
        "us-close",
        "us-close-strong",
        "usdinr"
      ],
      "labels": [
        "US market close (>0.3%)",
        "US strong close (>1.5%)",
        "USD/INR move (>0.2%, inverse)"
      ],
      "outcome": "gap",
      "n": 54,
      "hitRate": 90.7,
      "testN": 15,
      "testHitRate": 80,
      "avgMove": 0.829
    }
  ],
  "US": []
};
